<ul id="main_tabs" class="main-tabs">
	<li id="main_tab_details" class="first tab1 active">
		<a href="javascript:void(0)"><span><span>Description</span></span></a>
	</li>
	<li id="main_tab_images" class="tab2">
		<a href="javascript:void(0)"><span><span>Screenshots</span></span></a>
	</li>
	<li id="main_tab_order" class="last tab3">
		<a href="javascript:void(0)"><span><span>Pricing</span></span></a>
	</li>
</ul>