<?php
/*
* We can write some PHP to get 3 newest products, but I don't think this is belonged to FE team. Have any way * to do it?
*/
?>
<div class="sidebar__newtheme">

<div class="title">
	<strong><span><?php echo $this->__("New themes"); ?></span></strong>
	<ul class="action">
		<li class="previous"></li>
		<li class="next active"></li>
	</ul>
</div>

<ul class="sidebar__newtheme__list">
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
    <li class="item">
        <a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme" class="product-image"><img src="http://www.emthemes.com/media/catalog/product/cache/1/small_image/220x/17f82f742ffe127f42dca9de82fb58b1/l/a/layout_supermarket_01_home_default.png" alt="EM SuperStore - Premium Responsive Magento Theme"></a>
        <h3 class="product-name"><a href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="EM SuperStore - Premium Responsive Magento Theme">EM SuperStore - Premium Responsive Magento Theme</a></h3>
        <div class="overlay">
            <a class="details-link" href="http://www.emthemes.com/premium-magento-themes/em-superstore.html" title="theme details">theme details</a>
            <a class="screenshots-link" href="http://www.emthemes.com/quickview/images?id=319/" title="more screenshot">more screenshots</a>
            <div class="price-box">
                <span class="regular-price">
                    <span class="price">$79.00</span>
                </span>
            </div>
        </div>
    </li>
</ul>

</div>